name: Check test vectors

on: pull_request

jobs:
  verify:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: ['rust', 'json', 'zcash']
        include:
          - kind: 'rust'
            extension: 'rs'
            name: 'Rust'
          - kind: 'json'
            extension: 'json'
            name: 'JSON'
          - kind: 'zcash'
            extension: 'json'
            name: 'Bitcoin-flavoured JSON'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install gnome-keyring
        run: sudo apt-get install gnome-keyring

      - name: Install poetry
        run: pip install --user poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Regenerate test vectors
        run: ./regenerate.sh ${{ matrix.kind }} ${{ matrix.extension }}

      - name: Verify there are no changes
        run: git diff; git ls-files --others --exclude-standard; test -z "$(git status --porcelain)"
